### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by xieym217** [kianzarrin/HideTMPECrosswalks#15] opened 2020-07-10 13:38 UTC
After subscribing to hide crosswalks 3.0 (experimental), when the camera zooms in, the models of roads and buildings in the game will disappear.（as shown in these 2 pics）
![image](https://user-images.githubusercontent.com/51253008/87160230-3cbcbe80-c2f5-11ea-8a42-d45b398a3378.png)
![image](https://user-images.githubusercontent.com/51253008/87160238-3fb7af00-c2f5-11ea-99d9-55d8049a3be1.png)
[TMPE.log](https://github.com/CitiesSkylinesMods/HideCrosswalks/files/4903371/TMPE.log)
[RMCrosswalks.debug.log](https://github.com/CitiesSkylinesMods/HideCrosswalks/files/4903372/RMCrosswalks.debug.log)
[output_log.txt](https://github.com/CitiesSkylinesMods/HideCrosswalks/files/4903380/output_log.txt)

**Comment by kianzarrin** [comment] 2020-07-15 12:36
@xieym217 
So lets see if we are on the same page:
- if camera is far you can see roads
- if camera is close you can see roads.
- if camera is not too far and not too close you can't see roads.

I face this problem intermittently even if I don't have any mods. Are you sure this is caused by hide crossing mod?

**Comment by xieym217** [comment] 2020-07-15 12:40
actually after i unsubed advanced toolbar mod this afternoon the roads returned visible，thanks for your reply！

--------------原始邮件--------------
发件人："kianzarrin "<notifications@github.com&gt;;
发送时间：2020年7月15日(星期三) 晚上8:37
收件人："CitiesSkylinesMods/HideCrosswalks" <HideCrosswalks@noreply.github.com&gt;;
抄送："xieym217 "<xieym9@mail2.sysu.edu.cn&gt;;"Mention "<mention@noreply.github.com&gt;;
主题：Re: [CitiesSkylinesMods/HideCrosswalks] Bug report (#15)
-----------------------------------

 

 
@xieym217
 So lets see if we are on the same page:
  
if camera is far you can see roads
 
if camera is close you can see roads.
 
if camera is not too far and not too close you can't see roads.
  
I face this problem intermittently even if I don't have any mods. Are you sure this is caused by hide crossing mod?

**Comment by xieym217** [comment] 2020-07-15 13:54
After I unsubscribed ‘Advanced toolbar’ mod the roads returned visible，I think this mod may be incompatible with Advanced toolbar.

**Comment by kianzarrin** [comment] 2020-07-26 17:45
No this has nothing to do with any mod this is a base CS problem that happens intermittently and people blame the last mod they installed when they encountered the problem.
I complained to Paradox and they gave me this response:
> I have seen a few reports over the years of that blue road effect, as you say always sporadic. Here are some such reports:
https://steamcommunity.com/app/255710/discussions/0/3454730619119664245/
https://forum.paradoxplaza.com/forum/threads/closed-cities-skylines-steam-seeing-blue-roads-after-park-life-update.1101601/post-24298064
One other thing you might try is updating that nVidia driver:
https://www.nvidia.com/Download/index.aspx?lang=en-us

**Comment by kianzarrin** [comment] 2020-07-26 18:01
wait you have assertion failures in the log.

**Comment by xieym217** [comment] 2020-07-27 11:48
Got it. Huge thanks for your information.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "kianzarrin"; 
Date: 2020年7月27日(星期一) 凌晨1:45
To: "CitiesSkylinesMods/HideCrosswalks"; 
Cc: "xieym217"; "State change"; 
Subject: Re: [CitiesSkylinesMods/HideCrosswalks] Bug report (#15)

&nbsp;


 
No this has nothing to do with any mod this is a base CS problem that happens intermittently and people blame the last mod they installed when they encountered the problem.
 I complained to Paradox and they gave me this response:
  
I have seen a few reports over the years of that blue road effect, as you say always sporadic. Here are some such reports:
 https://steamcommunity.com/app/255710/discussions/0/3454730619119664245/
 https://forum.paradoxplaza.com/forum/threads/closed-cities-skylines-steam-seeing-blue-roads-after-park-life-update.1101601/post-24298064
 One other thing you might try is updating that nVidia driver:
 https://www.nvidia.com/Download/index.aspx?lang=en-us

**Comment by kianzarrin** [comment] 2020-08-19 06:50
So after looking into the log I can see its the problem of my mod.
relevant problems:
https://forum.paradoxplaza.com/forum/threads/game-crashing-on-menu-paradox-support-sent-me-here.1409430/

https://steamcommunity.com/sharedfiles/filedetails/?id=1939169189

https://steamcommunity.com/sharedfiles/filedetails/?id=1934023593&searchtext=hide+tmpe+crossings

on an irrelevant topic, I also need to update know issues WTR to harmony type load exception.

**Comment by kianzarrin** [comment] 2020-08-19 07:37
@xieym217  I can see from the log that `CachePrefabs() called ...` does not exist in the log. that means hide crossings was not loaded probabely due to an error caused by another mod during `OnCreate` cycle.

do you still have this problem? Did you figure out which mod is incompatible?

**Comment by xieym217** [comment] 2020-08-19 07:44
> @xieym217 I can see from the log that `CachePrefabs() called ...` does not exist in the log. that means hide crossings was not loaded probabely due to an error caused by another mod during `OnCreate` cycle.
> 
> do you still have this problem? Did you figure out which mod is incompatible?

I have no problem now after I unsub Advanced toolbar, but im not sure whether the problem is caused by it or not

**Comment by kianzarrin** [comment] 2020-08-19 08:27
No the problem can't be advanced toolbar.
I am closing this.

**Closed as completed by kianzarrin** 2020-08-19 08:27 UTC
